print('==Desafio 004==')
n = input('Digite algo -> ')
print('É um caractere valido?', n.isidentifier())
print('É Alfabético?', n.isalpha())
print('É Númerico?', n.isnumeric())
print('É Alfanúmerico?', n.isalnum())
print('Letras maiusculas?', n.isupper())
print('Letras minusculas?', n.islower())
print('É um espaço?', n.isspace())
print('É um número decimal?', n.isdecimal())
print('É um digito?', n.isdigit())
print('É MAIÚSCULO na primeira letra de cada palavra?', n.istitle())
