n= int(input('Entre com um número para ver a tabuada:'))
print('-'*12)
print('{} X {:2} = {}'.format(n, 1, n*1))
print('{} X {:2} = {}'.format(n, 2, n*2))
print('{} X {:2} = {}'.format(n, 3, n*3))
print('{} X {:2} = {}'.format(n, 4, n*4))
print('{} X {:2} = {}'.format(n, 5, n*5))
print('{} X {:2} = {}'.format(n, 6, n*6))
print('{} X {:2} = {}'.format(n, 7, n*7))
print('{} X {:2} = {}'.format(n, 8, n*8))
print('{} X {:2} = {}'.format(n, 9, n*9))
print('-'*12)